### PR TITLE
Image in texts

### PR DESCRIPTION
**Pull request by hugolz**
This version uses the topleft as anchor, but i don't like it
Please fix

### CODE REVIEW

**Comment by Bowarc** [comment]
Next:
Precompute the given bits to separate the new line in their own bits, + maybe even make it a defferent enum variant so the draw can react of it more cleanly !

For example if a TextBit is Text and the raw string is "hi\nHellow" have the precomputation output
```[Text("hi"), NewLine, Text("Hellow")]```

**Comment by Bowarc** [comment]
That being said, couldn't you use only one ggez::graphics::Text when there is no images on the row?

Please investigate

**Comment by hugolz** [comment]
> On draw you could also optimise it to use only one `ggez::graphics::Text` when there is not image variants used

Done too

**Comment by hugolz** [comment]
> That being said, couldn't you use only one ggez::graphics::Text when there is no images on the row?
> 
> Please investigate

Done,
i think it's ready now

**Pull request merged**
